version: "3.0"

services:
  # Web service layer
  nginx:
    image: nginx:latest
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php

  # Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "7777:7777"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=dbinstafive

  # Data persistence service layer
  mysql:
    image: mysql:5.7.22
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=dbinstafive
      - MYSQL_DATABASE=dbinstafive

volumes:
  db_data: